{
 "title": "KAFKA Dashboard CN",
 "description": "【中文版本】2024.05.20更新，基于Prometheus的kafka_exporter，KAFKA资源全面展示！包括KAFKA整体的资源状态，生产者与消费者关系，消息积压的明细信息，生产与消费的速率，以及各分区的积压与消费明细。https://grafana.com/orgs/starsliao/dashboards",
 "tags": [
  "Prometheus",
  "KAFKA"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(kafka_brokers,job)"
    }
   },
   {
    "name": "consumer_group",
    "label": "消费组",
    "query": {
     "query": "query_result(count by (consumergroup)(kafka_consumergroup_members{job=\"$job\",consumergroup!~\"__.*\"}))"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values(kafka_consumergroup_lag_sum{job=\"$job\", topic!~\"__.*\", consumergroup=~\"$consumer_group\"},topic)"
    }
   },
   {
    "name": "consumergroup_hide",
    "label": "consumergroup_hide",
    "query": {
     "query": "label_values(kafka_consumergroup_lag_sum{job=\"$job\", topic!~\"__.*\", topic=~\"$topic\", consumergroup!~\"__.*\"},consumergroup)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Brokers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_brokers{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "stat",
   "description": "包括无消费组消费的Topic",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_topic_partitions{job=\"$job\",topic !~\"__.*\"})"
    }
   ]
  },
  {
   "title": "分区数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_topic_partitions{job=\"$job\",topic !~\"__.*\"})"
    }
   ]
  },
  {
   "title": "消费组",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_consumergroup_members{job=\"$job\",consumergroup!~\"__.*\"})"
    }
   ]
  },
  {
   "title": "消费者",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_members{job=\"$job\",consumergroup!~\"__.*\"})"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_replicas{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "In Sync Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_in_sync_replica{job=\"$job\",name=\"$name\"})"
    }
   ]
  },
  {
   "title": "Partitions not on preferred node",
   "type": "stat",
   "description": "Partitions not on preferred node",
   "gridPos": { "h": 3, "w": 1, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_topic_partition_leader_is_preferred{job=\"$job\"}<1)"
    }
   ]
  },
  {
   "title": "每秒总生产",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(kafka_topic_partition_current_offset{job=\"$job\",topic !~ \"__.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "每秒总消费",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(kafka_consumergroup_current_offset{job=\"$job\"}[3m]))"
    }
   ]
  },
  {
   "title": "当前总积压",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag_sum{job=\"$job\"})"
    }
   ]
  },
  { "title": "消费者与Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "消费组(关联右侧Topic表格)",
   "type": "table",
   "description": "- 菜单为全部消费组、全部Topic时，该表格显示的是所有已关联Topic的消费组列表。\n- 在菜单中选择消费组后，该表格的右侧会显示该消费组会消费的Topic列表；而当前表格显示的是参与消费右侧所有topic的消费组列表。",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "kafka_consumergroup_members{job=\"$job\",consumergroup=~\"$consumergroup_hide\",consumergroup!~\"__.*\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic(关联左侧消费组表格)",
   "type": "table",
   "description": "- 菜单为全部消费组、全部Topic时，该表格显示的是所有已关联消费组的Topic列表。\n- 在菜单中选择topic后，该表格的左侧会显示消费该topic的消费者列表。",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 4 },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{job=\"$job\",topic !~\"__.*\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "消费组积压>100（关联消费组，Topic）",
   "type": "timeseries",
   "description": "No data为无积压超过100的消费组。",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag_sum{job=\"$job\",consumergroup=~\"$consumer_group\",consumergroup!~\"__.*\",topic!~\"__.*\"}) by (consumergroup, topic)>100",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Topic每秒生产（关联Topic）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_topic_partition_current_offset{job=\"$job\",topic !~ \"__.*\",topic=~\"$topic\"}[3m])) by (topic)>0",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "消费组每秒消费（关联消费组，Topic）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_consumergroup_current_offset{job=\"$job\",consumergroup=~\"$consumer_group\",topic=~\"$topic\",consumergroup!~\"__.*\",topic!~\"__.*\"}[3m])) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Topic维度：每秒被消费总数 - 每秒生产*消费组数(负值为该秒消费不足)",
   "type": "timeseries",
   "description": "在Topic维度展示每秒该Topic整体被消费的情况。",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_consumergroup_current_offset{job=\"$job\",topic=~\"$topic\",consumergroup!~\"__.*\",topic!~\"__.*\"}[3m])) by (topic) - sum(irate(kafka_topic_partition_current_offset{job=\"$job\",topic!~\"__.*\",topic=~\"$topic\"}[3m])) by (topic) * count(kafka_consumergroup_lag_sum{job=\"$job\",consumergroup!~\"__.*\",topic!~\"__.*\",topic=~\"$topic\"}) by(topic) != 0",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "无关联Topic的消费组列表（持续出现的消费者最需要关注）",
   "type": "timeseries",
   "description": "No data为所有消费组都关联了Topic",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (consumergroup,job) (kafka_consumergroup_members{job=\"$job\",consumergroup!~\"__.*\"}) unless sum by (consumergroup,job)(kafka_consumergroup_lag_sum{job=\"$job\",consumergroup!~\"__.*\",topic!~\"__.*\"}) ",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "无消费组消费的Topic（持续出现的Topic需要关注）",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (topic,job)(kafka_topic_partition_current_offset{job=\"$job\",topic !~\"__.*\"} - kafka_topic_partition_oldest_offset{job=\"$job\",topic !~\"__.*\"}) unless count by (topic,job)(kafka_consumergroup_lag_sum{job=\"$job\",consumergroup!~\"__.*\",topic!~\"__.*\"}) ",
     "legendFormat": "{{topic}} 总消息数"
    },
    {
     "expr": "sum by (topic,job)(irate(kafka_topic_partition_current_offset{job=\"$job\",topic !~ \"__.*\"}[3m])) unless count by (topic,job)(kafka_consumergroup_lag_sum{job=\"$job\",consumergroup!~\"__.*\",topic!~\"__.*\"}) ",
     "legendFormat": "{{topic}} 每秒生产"
    }
   ]
  },
  { "title": "分区维度【需指定消费组】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "消费组【$consumer_group】各分区【当前积压】",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{job=\"$job\",consumergroup=\"$consumer_group\",topic=~\"$topic\",consumergroup!~\"__.*\",topic!~\"__.*\"}) by (consumergroup, topic,partition)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}}) 分区:{{partition}}"
    }
   ]
  },
  {
   "title": "消费组【$consumer_group】各分区【每秒消费】",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(kafka_consumergroup_current_offset{job=\"$job\",consumergroup=\"$consumer_group\",topic=~\"$topic\",consumergroup!~\"__.*\",topic!~\"__.*\"}[3m])",
     "legendFormat": "{{consumergroup}} (topic: {{topic}}) 分区:{{partition}}"
    }
   ]
  }
 ]
}