services:
  gitlab:
    image: gitlab/gitlab-ce:18.3.0-ce.0
    container_name: gitlab
    restart: always
    hostname: '10.84.0.106'
    environment:
      TZ: Asia/Shanghai
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://10.84.0.106'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
    ports:
      - '880:80'
      - '8443:443'
      - '2224:22'
    volumes:
      - '/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro'
      - '/data/gitlab/config:/etc/gitlab'
      - '/data/gitlab/logs:/var/log/gitlab'
      - '/data/gitlab/data:/var/opt/gitlab'
    shm_size: '512m'
