{
 "title": "K8S Dashboard",
 "tags": [
  "Prometheus",
  "Kubernetes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "label": "节点",
    "query": {
     "query": "label_values(kubelet_node_name{node=~\"$Node\"},node)"
    }
   },
   {
    "name": "NameSpace",
    "label": "命名空间",
    "query": {
     "query": "label_values(kube_namespace_annotations{namespace=~\"$NameSpace\"},namespace)"
    }
   },
   {
    "name": "Container",
    "label": "微服务(容器名)",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$NameSpace\"},container)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$NameSpace\", container=~\"$Container\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "节点资源总览：所选节点:【$Node】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "节点内存信息",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
     "legendFormat": "总内存"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\",node=~\"^$Node$\"})",
     "legendFormat": "使用量"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})",
     "legendFormat": "请求量"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})",
     "legendFormat": "限制量"
    }
   ]
  },
  {
   "title": "节点CPU核数",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
     "legendFormat": "总核数"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\"}[2m]))",
     "legendFormat": "使用量"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})",
     "legendFormat": "请求量"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})",
     "legendFormat": "限制量"
    }
   ]
  },
  {
   "title": "节点存储信息",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * (sum(node_filesystem_size_bytes{device=~\"^/dev/.*$\",instance!~\"10.*\",instance=~\"^$Node$\"}) - sum(node_filesystem_free_bytes{device=~\"^/dev/.*$\",instance!~\"10.*\",instance=~\"^$Node$\"})) \r\n/ sum(node_filesystem_size_bytes{device=~\"^/dev/.*$\", instance!~\"10.*\",instance=~\"^$Node$\"})",
     "legendFormat": "使用率"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{device=~\"^/dev/.*$\",instance!~\"10.*\",instance=~\"^$Node$\"}) - sum(node_filesystem_free_bytes{device=~\"^/dev/.*$\",instance!~\"10.*\",instance=~\"^$Node$\"})",
     "legendFormat": "使用量"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{device=~\"^/dev/.*$\",instance!~\"10.*\",instance=~\"^$Node$\"})",
     "legendFormat": "总量"
    }
   ]
  },
  {
   "title": "命名空间资源统计",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_pod_info{node=~\"^$Node$\"}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{}) by(namespace)"
    },
    {
     "expr": "count by (namespace)({__name__=~\"kube_deployment_metadata_generation|kube_daemonset_metadata_generation|kube_statefulset_metadata_generation\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(kube_configmap_info{}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{}) by(namespace)",
     "legendFormat": "secret"
    }
   ]
  },
  {
   "title": "$NameSpace：网络总览（可关联节点与命名空间）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum (irate(container_network_receive_bytes_total{node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m]))*8",
     "legendFormat": "接收"
    },
    {
     "expr": "sum (irate(container_network_transmit_bytes_total{node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m]))*8",
     "legendFormat": "发送"
    }
   ]
  },
  {
   "title": "节点内存比例",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container!=\"\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
     "legendFormat": "内存请求率"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
     "legendFormat": "内存限制率"
    }
   ]
  },
  {
   "title": "节点CPU比例",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{container!=\"\",node=~\"^$Node$\"}[2m])) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
     "legendFormat": "CPU请求率"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
     "legendFormat": "CPU限制率"
    }
   ]
  },
  {
   "title": "节点与Pod",
   "type": "bargauge",
   "description": "集群节点数，节点POD数，节点POD上限",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(kube_node_info{})", "legendFormat": "节点数" },
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"})",
     "legendFormat": "Pod数"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\", unit=\"integer\",node=~\"^$Node$\"})",
     "legendFormat": "上限Pod"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "repeat": "origin_prometheus",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count({__name__=~\"kube_deployment_metadata_generation|kube_daemonset_metadata_generation|kube_statefulset_metadata_generation\"})",
     "legendFormat": "工作负载"
    },
    { "expr": "count(kube_pod_info{})", "legendFormat": "总Pod" },
    {
     "expr": "count by(key)(kube_node_spec_taint{key=~\"node-role.kubernetes.io.*\"})",
     "legendFormat": "默认污点"
    },
    {
     "expr": "count by()(kubelet_node_name{})",
     "legendFormat": "总节点"
    },
    {
     "expr": "count by()(kubelet_node_name{}) - count by()(kube_node_spec_taint{key!~\"node.kubernetes.io.*\"})",
     "legendFormat": "正常节点"
    },
    {
     "expr": "count by(key)(kube_node_spec_taint{key!~\"node-role.kubernetes.io.*\"})",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "内存使用量【$Node】",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
     "legendFormat": "总内存"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\",node=~\"^$Node$\"})",
     "legendFormat": "使用量"
    }
   ]
  },
  {
   "title": "CPU使用核【$Node】",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
     "legendFormat": "总核数"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\"}[2m]))",
     "legendFormat": "使用量"
    }
   ]
  },
  {
   "title": "Pod数与节点数【$Node】",
   "type": "timeseries",
   "description": "集群节点数，节点POD数，节点POD上限",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "count(kube_node_info{})", "legendFormat": "节点数" },
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"})",
     "legendFormat": "Pod数"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\", unit=\"integer\",node=~\"^$Node$\"})",
     "legendFormat": "上限Pod"
    }
   ]
  },
  {
   "title": "$Node：节点CPU明细",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{container!=\"\",node=~\"^$Node$\"}[2m]))by (node) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)*100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$Node：节点内存明细",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)*100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$Node：节点网络总览",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum (irate(container_network_receive_bytes_total{node=~\"^$Node$\"}[2m]))by (node) *8",
     "legendFormat": "流入:{{node}}"
    },
    {
     "expr": "sum (irate(container_network_transmit_bytes_total{node=~\"^$Node$\"}[2m]))by (node) *8",
     "legendFormat": "流出:{{node}}"
    }
   ]
  },
  {
   "title": "$Node：节点信息明细",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"}) by (node)",
     "legendFormat": "pod数"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{container!=\"\",node=~\"^$Node$\"}[2m])) by (node)"
    },
    {
     "expr": "kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"} - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"}) by (node) - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)",
     "legendFormat": "内存使用%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)",
     "legendFormat": "内存请求%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)",
     "legendFormat": "内存限制%"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{container!=\"\",node=~\"^$Node$\"}[2m]))by (node) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)",
     "legendFormat": "CPU使用%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)",
     "legendFormat": "CPU请求%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)",
     "legendFormat": "内存限制%"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\", unit=\"integer\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "Pod上限"
    }
   ]
  },
  {
   "title": "各命名空间CPU使用核(>0.5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container !=\"\",container!=\"POD\"}[2m])) by (namespace)>0.5",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "命名空间WSS内存使用(>1G)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container !=\"\",container!=\"POD\"}) by (namespace) > 1*1024*1024*1024",
     "legendFormat": "{{namespace} {{ pod }}"
    }
   ]
  },
  {
   "title": "PVC存储使用情况",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{})",
     "legendFormat": "{{namespace}}:{{ persistentvolumeclaim }}"
    },
    {
     "expr": "min by (namespace,persistentvolumeclaim) (kubelet_volume_stats_available_bytes{}) + max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{}) /(min by (namespace,persistentvolumeclaim) (kubelet_volume_stats_available_bytes{}) + max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{}))*100",
     "legendFormat": "{{namespace}}:{{ persistentvolumeclaim }}"
    },
    {
     "expr": "count by (namespace,persistentvolumeclaim)(kube_pod_spec_volumes_persistentvolumeclaims_info{})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pod资源明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Pod容器CPU核使用",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container, pod,node,namespace)",
     "legendFormat": "CPU使用：{{ pod }}"
    },
    {
     "expr": "max(max(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)) by(container)",
     "legendFormat": "Pod CPU限制：{{ container}}"
    }
   ]
  },
  {
   "title": "Pod容器CPU使用率(最大100%可关联节点)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\", container=~\"$Container\", container!=\"\", container!=\"POD\", node=~\"^$Node$\", namespace=~\"$NameSpace\"}[2m])) by (container, pod)\r\n/\r\nmax(kube_pod_container_resource_limits{pod=~\"$Pod\", container=~\"$Container\", resource=\"cpu\", node=~\"^$Node$\", namespace=~\"$NameSpace\"}) by (container, pod)\r\n* 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod容器内存使用率(可关联节点)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{pod=~\"$Pod\", container=~\"$Container\", container!=\"\", container!=\"POD\", node=~\"^$Node$\", namespace=~\"$NameSpace\"}) by (container, pod)\r\n/\r\nmax(kube_pod_container_resource_limits{pod=~\"$Pod\", container=~\"$Container\", resource=\"memory\", node=~\"^$Node$\", namespace=~\"$NameSpace\"}) by (container, pod)\r\n* 100",
     "legendFormat": "RSS：{{ pod }}"
    },
    {
     "expr": "max(container_memory_usage_bytes{pod=~\"$Pod\", container=~\"$Container\", container!=\"\", container!=\"POD\", node=~\"^$Node$\", namespace=~\"$NameSpace\"}) by (container, pod)\r\n/\r\nmax(kube_pod_container_resource_limits{pod=~\"$Pod\", container=~\"$Container\", resource=\"memory\", node=~\"^$Node$\", namespace=~\"$NameSpace\"}) by (container, pod)\r\n* 100",
     "legendFormat": "WSS：{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod容器WSS内存使用(可关联节点)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max (container_memory_working_set_bytes{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
     "legendFormat": "WSS：{{ pod }}"
    },
    {
     "expr": "max(max(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)) by(container)",
     "legendFormat": "Pod内存限制：{{ container}}"
    }
   ]
  },
  {
   "title": "Pod每秒网络带宽 (可关联节点)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "max(max(irate(container_network_receive_bytes_total{pod=~\"$Pod\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{pod=~\"$Pod\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(pod) *8",
     "legendFormat": "流入:{{ pod}}"
    },
    {
     "expr": "max(max(irate(container_network_transmit_bytes_total{pod=~\"$Pod\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{pod=~\"$Pod\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(pod) *8",
     "legendFormat": "流出:{{ pod}}"
    }
   ]
  },
  {
   "title": "微服务(容器名)资源总览：所选微服务:【$Container】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 }
  },
  {
   "title": "微服务(容器名)整体CPU使用核",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "CPU限制：{{ container}}"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container)",
     "legendFormat": "CPU核使用：{{ container}}"
    }
   ]
  },
  {
   "title": "微服务(容器名)整体内存使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "WSS：{{ container }}"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "内存限制：{{ container }}"
    },
    {
     "expr": "sum (container_memory_rss{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "RSS：{{ container }}"
    }
   ]
  },
  {
   "title": "微服务(容器名)每秒网络带宽 (可关联节点)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(sum(irate(container_network_receive_bytes_total{node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{namespace=~\"$NameSpace\",container =~\"$Container\"}) by(container) *8",
     "legendFormat": "流入:{{ container }}"
    },
    {
     "expr": "sum(sum(irate(container_network_transmit_bytes_total{node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{namespace=~\"$NameSpace\",container =~\"$Container\"}) by(container) *8",
     "legendFormat": "流出:{{ container }}"
    }
   ]
  },
  {
   "title": "微服务(容器名)Pod数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by(container,namespace)",
     "legendFormat": "{{namespace}}：{{ container }}"
    }
   ]
  },
  {
   "title": "微服务(容器名)平均CPU使用率(最大100%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=~\"$Container\",container!=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container)\r\n/\r\nsum(container_cpu_cfs_periods_total{container=~\"$Container\",container!=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)\r\n* 100",
     "legendFormat": "{{ container}}"
    }
   ]
  }
 ]
}