{
 "title": "Mysqld Exporter Dashboard",
 "description": "基于官方版本汉化，增加总览页，增加表大小行数统计，优化重要指标展示。",
 "tags": [
  "MySQL",
  "mysqld_exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(mysql_version_info,job)"
    }
   },
   { "name": "Pod", "label": "Pod", "query": { "query": "label_values(mysql_up,pod)" } },
   { "name": "interval", "label": "时间精度", "query": "1m,2m,3m,5m,10m" }
  ]
 },
 "panels": [
  { "title": "总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MySQL资源总览表",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" },
    {
     "expr": "rate(mysql_global_status_queries{}[$interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (mysql_info_schema_processlist_processes_by_user{})by(job)",
     "legendFormat": "用户连接数"
    },
    {
     "expr": "mysql_global_status_threads_running{} -0",
     "legendFormat": "活跃连接数"
    },
    {
     "expr": "sum (mysql_info_schema_processlist_threads{}) by(job)",
     "legendFormat": "非unknown线程数"
    },
    {
     "expr": "rate(mysql_global_status_bytes_received{}[$interval])",
     "legendFormat": "接收"
    },
    {
     "expr": "rate(mysql_global_status_bytes_sent{}[$interval])",
     "legendFormat": "发送"
    }
   ]
  },
  { "title": "全局", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "最大QPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_queries{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool",
   "type": "stat",
   "description": "**InnoDB Buffer Pool Size**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_innodb_buffer_pool_size{pod=~\"$Pod\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "InnoDB I/O",
   "type": "timeseries",
   "description": "**InnoDB I/O**\n\n_Data Writes_ - The total number of InnoDB data writes.\\\n_Data Reads_ - The total number of InnoDB data reads (OS file reads).\\\n_Log Writes_ - The number of physical writes to the InnoDB redo log file.\\\n_Data Fsyncs_ - The number of fsync() operations. The frequency of fsync() calls is influenced by the setting of the `innodb_flush_method` configuration option.",
   "gridPos": { "h": 13, "w": 18, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_data_reads{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "Data Reads"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_data_writes{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "Data Writes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_data_fsyncs{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "Data Fsyncs"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_log_writes{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "Log Writes"
    }
   ]
  },
  {
   "title": "运行时间",
   "type": "stat",
   "description": "自上次重新启动mysql服务器进程的运行时间。",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_uptime{pod=~\"$Pod\"}"
    }
   ]
  },
  {
   "title": "表占用空间概览Top10",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "topk(10, sum(mysql_info_schema_table_size{pod=~\"$Pod\", component!=\"data_free\"}) by (schema, table)) > 0",
     "legendFormat": "{{ schema }}.{{ table }}"
    }
   ]
  },
  {
   "title": "表数据量概览Top10",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "topk(10, sum(mysql_info_schema_table_rows{pod=~\"$Pod\"}) by (schema, table)) > 0",
     "legendFormat": "{{ schema }}.{{ table }}"
    }
   ]
  },
  {
   "title": "QPS/TPS",
   "type": "timeseries",
   "description": "QPS计算只包括客户端发送到服务器的语句，而不包括存储程序中执行的语句\n- 以下命令不被统计：\n* ``COM_PING``\n* ``COM_STATISTICS``\n* ``COM_STMT_PREPARE``\n* ``COM_STMT_CLOSE``\n* ``COM_STMT_RESET``",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_queries{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "QPS"
    },
    {
     "calculatedInterval": "10m",
     "expr": "sum(rate(mysql_global_status_commands_total{pod=~\"$Pod\",command=~\"(commit|rollback)\"}[$interval])) without (command)",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "用户连接数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mysql_info_schema_processlist_processes_by_user{pod=~\"$Pod\"}",
     "legendFormat": "{{mysql_user}}"
    }
   ]
  },
  {
   "title": "内存使用情况",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": " mysql_global_status_innodb_page_size{pod=~\"$Pod\"} * on (instance) mysql_global_status_buffer_pool_pages{pod=~\"$Pod\",state=\"data\"}",
     "legendFormat": "InnoDB Buffer Pool Data"
    },
    {
     "expr": "mysql_global_variables_innodb_log_buffer_size{pod=~\"$Pod\"}",
     "legendFormat": "InnoDB Log Buffer Size"
    },
    {
     "expr": "mysql_global_variables_innodb_additional_mem_pool_size{pod=~\"$Pod\"}",
     "legendFormat": "InnoDB Additional Memory Pool Size"
    },
    {
     "expr": "mysql_global_status_innodb_mem_dictionary{pod=~\"$Pod\"}",
     "legendFormat": "InnoDB Dictionary Size"
    },
    {
     "expr": "mysql_global_variables_key_buffer_size{pod=~\"$Pod\"}",
     "legendFormat": "Key Buffer Size"
    },
    {
     "expr": "mysql_global_variables_query_cache_size{pod=~\"$Pod\"}",
     "legendFormat": "Query Cache Size"
    },
    {
     "expr": "mysql_global_status_innodb_mem_adaptive_hash{pod=~\"$Pod\"}",
     "legendFormat": "Adaptive Hash Index Size"
    },
    {
     "expr": "mysql_global_variables_tokudb_cache_size{pod=~\"$Pod\"}",
     "legendFormat": "TokuDB Cache Size"
    }
   ]
  },
  {
   "title": "Processlist列表",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_processlist_threads{pod=~\"$Pod\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "慢查询", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "慢排序",
   "type": "timeseries",
   "description": "Sort_scan 和 Sort_range\n查询做排序，不论是因为 order by 还是 group by（除了使用了 order by NULL 的 group by），主要都是下面的三步：\n通过 where 条件找到记录\n排序\n按排好的顺序读取记录\n如果第二步不被跳过，那么第三步中就会有 Sort_scan 或 Sort_range。如果第一步是 Select_scan，那么第三步将是 Sort_scan，如果第一步是 Select_range，那么第三步会是 Sort_range。但 Sort_scan 和 Sort_range 其实没有功能上的区别，都是将需要的记录按顺序读出来，所以性能也是一样的。\nSort_merge_passes\nSort_merge_passes 包括两步。MySQL 首先会尝试在内存中做排序，使用的内存大小由系统变量 Sort_buffer_size 决定，如果它的大小不够把所有的记录都读到内存中，MySQL 就会把每次在内存中排序的结果存到临时文件中，等 MySQL 找到所有记录之后，再把临时文件中的记录做一次排序。这再次排序就会增加 Sort_merge_passes。实际上，MySQL 会用另一个临时文件来存再次排序的结果，所以通常会看到 Sort_merge_passes 增加的数值是建临时文件数的两倍。因为用到了临时文件，所以速度可能会比较慢，增加 Sort_buffer_size 会减少 Sort_merge_passes 和 创建临时文件的次数。但盲目的增加 Sort_buffer_size 并不一定能提高速度。",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_rows{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "Sort Rows"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_range{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "范围排序"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_merge_passes{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "合并排序"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_scan{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "全表排序"
    }
   ]
  },
  {
   "title": "每分钟慢查询数量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "delta(mysql_global_status_slow_queries{pod=~\"$Pod\"}[1m])",
     "legendFormat": "慢查询次数"
    }
   ]
  },
  {
   "title": "临时对象",
   "type": "timeseries",
   "description": "此图显示有关mysql服务器创建的临时对象的信息：临时表、临时文件和在磁盘而不是内存中创建的临时表。就像排序数据一样，这很容易被过度分析。最严重的是在磁盘上创建的临时表。",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_created_tmp_tables{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "内存中的临时表"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_created_tmp_disk_tables{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "硬盘中的临时表"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_created_tmp_files{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "临时文件"
    }
   ]
  },
  {
   "title": "Mysql慢扫描类型",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_full_join{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "多表全表扫描（join查询未使用索引）"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_full_range_join{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "Select Full Range Join"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_range{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "范围查询（需要从硬盘读表在一段范围内的所有行）"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_range_check{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "范围查询检查（如果可以那么会使用范围查询，如果不行仍会使用全表扫描）"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_scan{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "全表扫描"
    }
   ]
  },
  { "title": "连接", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "MySQL Connections",
   "type": "timeseries",
   "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_threads_connected{pod=~\"$Pod\"}",
     "legendFormat": "Connections"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_max_used_connections{pod=~\"$Pod\"}",
     "legendFormat": "Max Used Connections"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_max_connections{pod=~\"$Pod\"}",
     "legendFormat": "Max Connections"
    }
   ]
  },
  {
   "title": "当前活跃的连接数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_threads_running{pod=~\"$Pod\"}",
     "legendFormat": "当前活跃的连接数"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_connection_errors_total{pod=~\"$Pod\"}[1m]) > 0",
     "legendFormat": "ERROR:{{error}}"
    }
   ]
  },
  {
   "title": "线程缓存",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_thread_cache_size{pod=~\"$Pod\"}",
     "legendFormat": "线程缓存配置数量（自动调整）"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_threads_cached{pod=~\"$Pod\"}",
     "legendFormat": "实际缓存线程数"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_threads_created{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "新创建的线程数（单个时间单元内）"
    }
   ]
  },
  {
   "title": "主从复制延迟(从库才有数据)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_slave_status_seconds_behind_master{pod=~\"$Pod\"}",
     "legendFormat": "主从复制延迟"
    }
   ]
  },
  { "title": "连接中断与表锁", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "InnoDB行锁等待",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(mysql_global_status_innodb_row_lock_waits{pod=~\"$Pod\"}[1m])",
     "legendFormat": " 每分钟行锁等待数"
    },
    {
     "expr": "delta(mysql_global_status_innodb_row_lock_time{pod=~\"$Pod\"}[1m])/1000",
     "legendFormat": "每分钟行锁等待时间(s)"
    },
    {
     "expr": "(rate(mysql_global_status_innodb_row_lock_time{pod=~\"$Pod\"}[$interval])/1000)/rate(mysql_global_status_innodb_row_lock_waits{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "平均行锁等待时间(s)"
    }
   ]
  },
  {
   "title": "InnoDB 每分钟死锁",
   "type": "timeseries",
   "description": "**InnoDB Deadlocks**\n\nA deadlock in MySQL happens when two or more transactions mutually hold and request for locks, creating a cycle of dependencies. In a transaction system, deadlocks are a fact of life and not completely avoidable. InnoDB automatically detects transaction deadlocks, rollbacks a transaction immediately and returns an error.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_info_schema_innodb_metrics_lock_lock_deadlocks_total{pod=~\"$Pod\"}[1m])",
     "legendFormat": "Deadlocks"
    }
   ]
  },
  {
   "title": "中断的连接",
   "type": "timeseries",
   "description": "当一个主机连接到mysql时，连接被中断（例如密码修改），mysql将该信息保存在一个系统表中。\n\n如果连接失败请求的数量达到max_connect_errors的值，mysqld将假定有问题并阻止主机进一步连接。\n\n要再次允许来自该主机的连接，需要发出“flush hosts”请求。",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aborted_connects{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "中断的连接 (被打断)"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aborted_clients{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "中断的客户端 (超时)"
    }
   ]
  },
  {
   "title": "表锁",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_table_locks_immediate{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "表锁执行数量"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_table_locks_waited{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "表锁等待数量"
    },
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_table_locks_waited{pod=~\"$Pod\"}[5m])",
     "legendFormat": "5分钟表锁等待数量"
    }
   ]
  },
  { "title": "操作类型, 处理器", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "MySQL 命令执行频率排行",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, rate(mysql_global_status_commands_total{pod=~\"$Pod\"}[$interval])>0)",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "处理器",
   "type": "timeseries",
   "description": "- read_rnd_next：在数据文件中读下一行的请求数。如果你正进行大量的表扫描，该值较高。通常说明你的表索引不正确或写入的查询没有利用索引。\n- read_next：按照键顺序读下一行的请求数。如果你用范围约束或如果执行索引扫描来查询索引列，该值增加。\n- read_key：根据键读一行的请求数。如果较高，说明查询和表的索引正确。\n- write：请求向表中插入一行的次数。 \n- read_rnd：根据固定位置读一行的请求数。如果你正执行大量查询并需要对结果进行排序该值较高。你可能使用了大量需要MySQL扫描整个表的查询或你的连接没有正确使用索引。\n- external_lock：此变量与锁定操作数量有关，主要是在表访问的开始和结束时起作用。\n- update：请求更新表中一行的次数。 \n- read_prev：按照键顺序读前一行的请求数。该读方法主要用于优化ORDER BY … DESC。\n- read_first：索引中第一条被读的次数。如果较高，它建议服务器正执行大量全索引扫描；例如，SELECT col1 FROM foo，假定col1有索引。\n- delete：请求从表中删除行的次数。\n- read_last：根据键读最后一行的请求数。",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_handlers_total{pod=~\"$Pod\", handler!~\"commit|rollback|savepoint.*|prepare\"}[$interval])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "事务处理器",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_handlers_total{pod=~\"$Pod\", handler=~\"commit|rollback|savepoint.*|prepare\"}[$interval])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  { "title": "网络", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "传输速度",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_received{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "接受"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_sent{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "发送"
    }
   ]
  },
  {
   "title": "MySQL每小时流量使用情况",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_bytes_received{pod=~\"$Pod\"}[1h])",
     "legendFormat": "接收"
    },
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_bytes_sent{pod=~\"$Pod\"}[1h])",
     "legendFormat": "发送"
    }
   ]
  },
  { "title": "缓存", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "Innodb_buffer_pool命中率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1- mysql_global_status_innodb_buffer_pool_reads{pod=~\"$Pod\"} / mysql_global_status_innodb_buffer_pool_read_requests{pod=~\"$Pod\"} ",
     "legendFormat": "命中率"
    }
   ]
  },
  {
   "title": "InnoDB 缓冲池逻辑读请求数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_buffer_pool_read_requests{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "Read Requests"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_buffer_pool_write_requests{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "Write Requests"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_buffer_pool_reads{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "Disk Reads"
    }
   ]
  },
  {
   "title": "MySQL Table Open Cache Status",
   "type": "timeseries",
   "description": "**MySQL Table Open Cache Status**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_opened_tables{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "Openings"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_hits{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_misses{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "Misses"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_overflows{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "Misses due to Overflows"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_hits{pod=~\"$Pod\"}[$interval])/(rate(mysql_global_status_table_open_cache_hits{pod=~\"$Pod\"}[$interval])+rate(mysql_global_status_table_open_cache_misses{pod=~\"$Pod\"}[$interval]))",
     "legendFormat": "Table Open Cache Hit Ratio"
    }
   ]
  },
  {
   "title": "MySQL Table Definition Cache",
   "type": "timeseries",
   "description": "**MySQL Table Definition Cache**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_table_definitions{pod=~\"$Pod\"}",
     "legendFormat": "Open Table Definitions"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_table_definition_cache{pod=~\"$Pod\"}",
     "legendFormat": "Table Definitions Cache Size"
    },
    {
     "expr": "rate(mysql_global_status_opened_table_definitions{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "Opened Table Definitions"
    }
   ]
  },
  {
   "title": "InnoDB 缓冲池内存使用详情",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_innodb_buffer_pool_bytes_data{pod=~\"$Pod\"}",
     "legendFormat": "Data Total"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_innodb_buffer_pool_bytes_dirty{pod=~\"$Pod\"}",
     "legendFormat": "Data Dirty"
    }
   ]
  },
  { "title": "表", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 148 } },
  {
   "title": "MySQL File Openings",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_opened_files{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "Openings"
    }
   ]
  },
  {
   "title": "MySQL Open Files",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_files{pod=~\"$Pod\"}",
     "legendFormat": "Open Files"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_open_files_limit{pod=~\"$Pod\"}",
     "legendFormat": "Open Files Limit"
    },
    {
     "expr": "mysql_global_status_innodb_num_open_files{pod=~\"$Pod\"}",
     "legendFormat": "InnoDB Open Files"
    }
   ]
  },
  {
   "title": "InnoDB Row Operations",
   "type": "timeseries",
   "description": "**InnoDB Row Operations**\n\nThis graph allows you to see which operations occur and the number of rows affected per operation. A graph like Queries Per Second will give you an idea of queries, but one query could effect millions of rows.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_row_ops_total{pod=~\"$Pod\"}[$interval])",
     "legendFormat": "Rows {{ operation }}"
    }
   ]
  },
  {
   "title": "MySQL Open Tables",
   "type": "timeseries",
   "description": "**MySQL Open Tables**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_tables{pod=~\"$Pod\"}",
     "legendFormat": "Open Tables"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_table_open_cache{pod=~\"$Pod\"}",
     "legendFormat": "Table Open Cache"
    }
   ]
  },
  {
   "title": "InnoDB Log File Usage Hourly",
   "type": "timeseries",
   "description": "**InnoDB Log File Usage Hourly**\n\nAlong with the buffer pool size, `innodb_log_file_size` is the most important setting when we are working with InnoDB. This graph shows how much data was written to InnoDB's redo logs over each hour. When the InnoDB log files are full, InnoDB needs to flush the modified pages from memory to disk.\n\nThe rules of the thumb is to keep one hour of traffic in those logs and let the checkpointing perform its work as smooth as possible. If you don't do this, InnoDB will do synchronous flushing at the worst possible time, ie when you are busiest.\n\nThis graph can help guide you in setting the correct `innodb_log_file_size`.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_innodb_os_log_written{pod=~\"$Pod\"}[1h])",
     "legendFormat": "Data Written"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_log_files_in_group{pod=~\"$Pod\"} * mysql_global_variables_innodb_log_file_size{pod=~\"$Pod\"}",
     "legendFormat": "Total Size of InnoDB Log Files"
    }
   ]
  }
 ]
}