services:
  jenkins:
    image: registry.cn-shanghai.aliyuncs.com/qwx_images/jenkins:2.523
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /data/jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    restart: unless-stopped
    privileged: true