{
 "title": "Etcd Cluster CN",
 "description": "Etcd 集群概览显示从 etcd Prometheus 指标端点抓取的详细信息。",
 "tags": [
  "etcd",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(etcd_cluster_version,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"$job\"}, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "2m,5m,10m,30m,1h,3h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "是否存在 Leader",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_has_leader{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "Has Leader"
    }
   ]
  },
  {
   "title": "集群成员数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etcd_server_id{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "Members"
    }
   ]
  },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$job\"} / etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$job\"})*100"
    },
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\",job=~\"$job\"}"
    },
    {
     "expr": "sum(etcd_debugging_mvcc_keys_total{instance=~\"$instance\",job=~\"$job\"}) by (instance)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\"}[5m])) by (instance, le))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\"}[5m])) by (instance, le))"
    },
    {
     "expr": "sum(etcd_server_is_leader{instance=~\"$instance\",job=~\"$job\"}) by (instance)"
    },
    {
     "expr": "sum(etcd_debugging_mvcc_db_compaction_keys_total{instance=~\"$instance\",job=~\"$job\"}) by (instance)"
    },
    {
     "expr": "(etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$job\"} / etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$job\"})*100",
     "legendFormat": "Urgent Defragmentation"
    },
    {
     "expr": "etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$job\"} - etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "DB Capacity"
    },
    {
     "expr": "etcd_server_quota_backend_bytes{instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Leader 变更次数（最大）",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "Leader Changes"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Etcd Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  etcd_cluster_version{cluster_version=\"3.5\"}\r\n  * on() group_left(version) \r\n  vector(3.5)\r\n)",
     "legendFormat": "Etcd Version"
    }
   ]
  },
  {
   "title": "Etcd gRPC 出站速率",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{instance=~\"$instance\",job=~\"$job\"}[$interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "etcd 集群内节点之间的入站流量",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total{instance=~\"$instance\",job=~\"$job\"}[$interval])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "etcd 集群内节点之间的出站流量",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{instance=~\"$instance\",job=~\"$job\"}[$interval])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Etcd gRPC 入站速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{instance=~\"$instance\",job=~\"$job\"}[$interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Keys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Etcd 当前键总数（包含活跃 key 和过期 key）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_keys_total{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Etcd Key 写入与删除速率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(etcd_mvcc_put_total{instance=~\"$instance\",job=~\"$job\"}[$interval])",
     "legendFormat": "{{ instance }} puts/s"
    },
    {
     "expr": "rate(etcd_debugging_mvcc_delete_total{instance=~\"$instance\",job=~\"$job\"}[$interval])",
     "legendFormat": "{{ instance }} deletes/s"
    }
   ]
  },
  {
   "title": "最近一次 compaction 操作处理的 key 总数",
   "type": "timeseries",
   "description": "Compaction 是 etcd 用于清理旧版本 key 的机制，以释放存储空间。",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_compaction_keys_total{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{ instance  }}"
    }
   ]
  },
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Etcd 内存使用量（RSS）",
   "type": "timeseries",
   "description": "目标进程当前占用的 常驻内存大小（RSS，Resident Set Size），单位为 字节（bytes）\n\nRSS 指进程在物理内存中实际使用的部分，不包括 swap 和共享库未加载部分。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Etcd 数据库总大小 / 实际使用大小",
   "type": "timeseries",
   "description": "总空间大小：包括空洞和未清理的数据\n已用空间大小：排除了空洞和未清理的数据，实际有数据的大小\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{ instance }} 总空间大小"
    },
    {
     "expr": "etcd_mvcc_db_total_size_in_use_in_bytes{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{ instance }} 已用空间大小"
    }
   ]
  },
  {
   "title": "etcd 磁盘写入性能指标（fsync & commit）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(etcd_disk_wal_fsync_duration_seconds_sum{instance=~\"$instance\",job=~\"$job\"}[$interval])",
     "legendFormat": "{{ instance }} WAL 同步到磁盘的总耗时"
    },
    {
     "expr": "rate(etcd_disk_backend_commit_duration_seconds_sum{instance=~\"$instance\",job=~\"$job\"}[$interval])",
     "legendFormat": "{{ instance }} 提交事务到磁盘的总耗时"
    }
   ]
  },
  {
   "title": "etcd 磁盘操作 99% 延迟（WAL fsync & Backend commit）",
   "type": "timeseries",
   "description": "WAL 同步操作耗时的高延迟分位值，代表大部分写操作中“最慢的1%”的耗时。\n\n体现了 WAL fsync 在磁盘上的性能表现，越低越好，越高说明磁盘同步可能存在瓶颈。\n\n“提交事务到磁盘的总延迟”是指 etcd 把事务写入并持久化到底层存储过程中的耗时。\n\n耗时包括了 etcd 后端完成一次事务写入操作（commit）的整个磁盘延迟。\n不是所有操作的平均耗时，而是 99% 的操作耗时都不会超过这个值，体现的是 尾部延迟（tail latency）。",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\"}[$interval])) by (instance, le))",
     "legendFormat": "{{ instance }} WAL 同步操作耗时的高延迟分位值"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\"}[$interval])) by (instance, le))",
     "legendFormat": "{{ instance }}  提交事务到磁盘的总延迟"
    }
   ]
  },
  {
   "title": "etcd 节点心跳发送失败次数 & 健康检查失败次数",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "etcd_server_heartbeat_send_failures_total{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{ instance }} etcd 发送心跳失败次数"
    },
    {
     "expr": "etcd_server_health_failures{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{ instance }} etcd 健康检查失败次数"
    }
   ]
  },
  {
   "title": "etcd 慢操作统计（Apply & Read Index）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "etcd_server_slow_apply_total{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{ instance }} etcd apply 操作的慢请求总次数"
    },
    {
     "expr": "etcd_server_slow_read_indexes_total{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{ instance }} etcd 读取索引操作的慢请求总次数"
    }
   ]
  },
  {
   "title": "etcd 磁盘碎片整理耗时趋势",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(etcd_disk_backend_defrag_duration_seconds_sum{instance=~\"$instance\",job=~\"$job\"}[$interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "etcd 快照保存耗时速率（集群总和）",
   "type": "timeseries",
   "description": "快照持续时间（snapshot_save_total_duration_seconds）异常长表明磁盘存在问题，并可能导致集群不稳定。",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_debugging_snap_save_total_duration_seconds_sum{instance=~\"$instance\",job=~\"$job\"}[$interval]))",
     "legendFormat": "快照保存操作的总延迟分布"
    }
   ]
  },
  {
   "title": "etcd Raft提议处理状态统计（失败、积压、提交、应用）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total{instance=~\"$instance\",job=~\"$job\"}[$interval]))",
     "legendFormat": "提议失败速率"
    },
    {
     "expr": "sum(etcd_server_proposals_pending{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "排队提议数"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{instance=~\"$instance\",job=~\"$job\"}[$interval]))",
     "legendFormat": "提议提交速率"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{instance=~\"$instance\",job=~\"$job\"}[$interval]))",
     "legendFormat": "提议应用速率"
    }
   ]
  },
  {
   "title": "etcd 活跃流连接数（Watch & Lease ）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\",instance=~\"$instance\",job=~\"$job\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\",instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "etcd Watch 服务当前活跃的双向流连接数"
    },
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\",instance=~\"$instance\",job=~\"$job\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\",instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "etcd Lease 服务当前活跃的双向流连接数"
    }
   ]
  },
  {
   "title": "etcd 后端存储压缩键速率",
   "type": "timeseries",
   "description": "etcd 后端存储数据库压缩过程中，被压缩的键的速率。\n压缩（compaction）是 etcd 用来清理旧版本数据、减少存储空间和提高查询效率的关键操作。\n\n速率越高，说明压缩活动越频繁或者压缩的范围越大。",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(etcd_debugging_mvcc_db_compaction_keys_total{instance=~\"$instance\",job=~\"$job\"}[$interval])",
     "legendFormat": "{{ instance }} 压缩速率（每秒处理键数）"
    }
   ]
  },
  {
   "title": "过去 24 小时内 etcd 集群 Leader 的切换次数。",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{instance=~\"$instance\",job=~\"$job\"}[1d])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "正在等待处理的提议（Proposals）数量",
   "type": "timeseries",
   "description": "表示有多少提案正在排队等待提交。待提交提案数量增加表明客户端负载过高或成员无法提交提案。",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(etcd_server_proposals_pending{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "Proposals Pending"
    }
   ]
  },
  {
   "title": "已提交提案总数",
   "type": "timeseries",
   "description": "proposals_committed_total 记录已提交的共识提案总数。若集群健康，该指标应随时间持续增长。健康的 etcd 集群中，多个成员可能暂时存在提案总数差异，原因包括：启动后从节点恢复数据、落后于领导者节点，或是领导者节点（因此拥有最多提交数）。需监控集群所有成员的该指标——若单个成员与领导者持续存在较大滞后，表明该成员运行缓慢或异常。\n\nproposals_applied_total 记录已应用的共识提案总数。etcd 服务器会异步应用每个已提交提案。正常情况下，proposals_committed_total 与 proposals_applied_total 的差值应保持较小范围（高负载下通常不超过数千）。若两者差值持续增大，表明 etcd 服务器过载，可能因执行繁重的范围查询或大型事务操作等昂贵查询所致。",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{instance=~\"$instance\",job=~\"$job\"}[$interval]))",
     "legendFormat": "已提交"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{instance=~\"$instance\",job=~\"$job\"}[$interval]))",
     "legendFormat": "已应用总数"
    }
   ]
  },
  {
   "title": "RPC 速率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\",instance=~\"$instance\",job=~\"$job\"}[$interval]))",
     "legendFormat": "RPC 速率"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\",instance=~\"$instance\",job=~\"$job\"}[$interval]))",
     "legendFormat": "RPC 失败率"
    }
   ]
  },
  {
   "title": "gRPC网络",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_client_grpc_received_bytes_total{instance=~\"$instance\",job=~\"$job\"}[$interval]))",
     "legendFormat": "已接收字节数"
    },
    {
     "expr": "sum(rate(etcd_network_client_grpc_sent_bytes_total{instance=~\"$instance\",job=~\"$job\"}[$interval]))",
     "legendFormat": "已发送字节数"
    }
   ]
  }
 ]
}