apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: higress-console-ingress
  namespace: higress-system
  annotations:
    higress.io/enable-rewrite: "true"
    higress.io/rewrite-path: /
spec:
  ingressClassName: higress
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: higress-console
            port:
              number: 8080
